spring:
  datasource:
    #   数据源基本配置
    username: root
    password: Zbawq123.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.93.124.232

server:
  port: 8083


